### ISSUE TITLE
Missing splat default

### ISSUE THREAD

**Issue by Darcness** [Dies-Irae-mu/game#43]
Repro Steps
1. New character that has not entered CG yet
2. +sheet

Expected outcome:
Sheet displays, no errors

Actual outcome:
Sheet displays, but also:
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/game/lib/python3.12/site-packages/evennia/commands/cmdhandler.py", line 629, in _run_command
    ret = cmd.func()
          ^^^^^^^^^^
  File "/root/game/commands/CmdSheet.py", line 511, in func
    if splat.lower() == 'mortal':
       ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'

An untrapped error occurred.
(Traceback was logged 24-12-26 21:17:35).
```

**Comment by soma-satoro** [comment]
This now provides the following error message:
'You must set a splat to initialize your sheet. Use +selfstat splat=<Splat> or ask staff to set it.'
![image](https://github.com/user-attachments/assets/8a1eb50c-7c34-4ffa-b9f1-443d751a5c5c)
