### ISSUE TITLE
conviction and Instinct not saving on Vampire Sheet

### ISSUE THREAD

**Issue by Kittenapped** [Dies-Irae-mu/game#55]
I am trying to set my conviction and instinct. It claims it is saved but it is not displaying on my sheet
![Screenshot (180)](https://github.com/user-attachments/assets/469fc8e2-5386-487a-a5a1-df9b03dd67f4)
![Screenshot (181)](https://github.com/user-attachments/assets/218ab5c8-2242-4ebc-ae71-ba948d722cb3)

**Comment by Kittenapped** [comment]
Road is also not updating when I attempt to set it to reflect what level of the Path/Road of Enlightenment I am on

**Comment by soma-satoro** [comment]
Resolved, reworked virtues and road into a section called Pools & Virtues, which includes Blood, Willpower, Road, your virtues, and on Shifter characters includes Renown, Rage, Gnosis, and Willpower.
