### ISSUE TITLE
Apecraft's Blessing

### ISSUE THREAD

**Issue by Darcness** [Dies-Irae-mu/game#57]
Repro Steps
1.  The gift `Apecraft's Blessings` did not exist.
2. Gift is added as `Apecraft's Blessing` (note the missing 's')
3. `selfstat Apecraft's Blessing=1` <--- Successful, shows as `Apecraft's Blessing...1`
4. Gift is edited by staff to `Apecraft's Blessings` (correct spelling)
5. `selfstat Apecraft's Blessing=` (To remove it) <---- Fails: `Stat 'Apecraft's Blessings' not found.'
6. `selfstat Apecraft's Blessings=` (Maybe remove it this way?) <--- Fails: Stat `Apecraft's Blessings' not found.`
7. `selfstat Apecraft's Blessings=1` (Maybe adding the new one will get rid of the old one?) <--- Succeeds, buuuuut:
```
--------- Gifts --------- 
Apecraft's Blessing...1  
Apecraft's Bless......1
```

**Comment by Darcness** [comment]
Note: This is on Danilo, if it is a character-specific issue

**Comment by soma-satoro** [comment]
This appears to be a character-specific issue. I attempted this on my staff bit and on a couple different PC bits. I removed it from your sheet, should be good.
