### ISSUE TITLE
selfstat nature

### ISSUE THREAD

**Issue by Darcness** [Dies-Irae-mu/game#58]
Repro Steps:
1. `selfstat Nature=Loner`

Expected Behavior:
`Updated Nature to Loner`

Actual Behavior:
`Value 'Loner' is not valid for stat 'Nature'.  Valid values are: [1, 2, 3, 4, 5]`

Notes:
You can get to the 'Nature' field by calling it 'Nature Archetype', and I assume that the 'Nature' stat represents a Sorc Path or something.  'Nature' should resolve to the archetype, and the other thing should be 'Nature Path' (or something appropriate to that stat), because the Nature archetype is something _every character has_.  It should be easy to set.

**Comment by soma-satoro** [comment]
Resolved, Nature (the Changeling Realm) is now titled 'Nature-Realm,' whereas Nature Archetype has become 'Nature.'
