### ISSUE TITLE
Rituals Background not showing for Vampires

### ISSUE THREAD

**Issue by Hierodule** [Dies-Irae-mu/game#61]
When utilising +selfstat Rituals=<value> on a vampire sheet, I got a message it had been applied, but found no change on my sheet. Suspect it is confusing it with the Werewolf Rituals Knowledge.

As a work-around, using the Werewolf "Rites" background in lieu of Rituals does work.

**Comment by soma-satoro** [comment]
Resolved, this has been renamed 'Ritae.'
