### ISSUE TITLE
Flight missing from Corax

### ISSUE THREAD

**Issue by Kittenapped** [Dies-Irae-mu/game#62]
The Flight Ability is currently missing from the Corax sheet. I believe it is considered a primary and should be listed under Talents. 

![Screenshot (231)](https://github.com/user-attachments/assets/d9fa0eb8-9020-4b08-8562-9339daf6b76e)

**Comment by soma-satoro** [comment]
resolved, flight has been added for Corax, Camazotz, some Mokole, and the Gargoyle vampire clan.
