### ISSUE TITLE
Unable to +gain Willpower?

### ISSUE THREAD

**Issue by Darcness** [Dies-Irae-mu/game#63]
Repro Steps:
1. Have 1 remaining Willpower: `Willpower..........1(7)`
2. `+gain Willpower=6/gimme`

Expected Outcome:
`You have gained 6 points of Willpower. Reason: gimme`

Actual Outcome:
`You are already at maximum willpower (7).`

Notes:
If I `+spend gnosis=1`, then `+gain gnosis=1` works.  It seems to be something specific to my Willpower? (PC: Danilo)  I did not spend to get my Willpower where it is, it just appeared that way.

**Comment by soma-satoro** [comment]
![image](https://github.com/user-attachments/assets/44a30abe-5a92-4482-bc8f-dcc7bd0425ce)
![image](https://github.com/user-attachments/assets/38eb0be4-b22a-4cd4-8405-d4407d02f043)

Resolved! Also made the pools and virtues bit look a little better.
